apiVersion: v1
kind: Secret
metadata:
  name: i27-helpdesk-gateway-secret
  namespace: ${NAMESPACE}
stringData:
    JWT_SECRET: "{{JWT_SECRET}}"

    # key: value correct way
    # key=value : value , wrong way